### ISSUE TITLE
Wrong clan closings

### ISSUE THREAD

**Issue by trempetic92** [michal-kapala/25tolife-website#2]
https://github.com/25-To-Life/25tolife-website/blob/724ee1e8bd03ab0bccb858ffca6f1e1b33869ddc/src/routes/stats/%5Bname%5D.svelte#L78

Should be < >

**Comment by michal-kapala** [comment]
Needs a font change in order to look decent due to vertical character padding, I might consider this along with #3 and #4 after #1 which is a major rewrite
